language: node_js
node_js:
- stable
branches:
  only: master
before_install:
- ruby -e "require 'pp'; pp RbConfig::CONFIG.values_at('rubyhdrdir', 'rubyarchhdrdir', 'libdir', 'LIBRUBY', 'LIBS')"
script:
- yarn test
cache: yarn
